### ISSUE TITLE
localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by hemedani** [benawad/graphql-ts-server-boilerplate#10]
I have this error when running `yarn test`
```shell
 FAIL  src/modules/user/logout/logout.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/modules/user/forgotPassword/forgotPassword.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/modules/user/register/createConfirmEmailLink.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/modules/user/register/register.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/routes/confirmEmail.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/modules/user/me/me.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  src/modules/user/login/login.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)
```

**Comment by benawad** [comment]
does yarn start work for you?

**Comment by philkeys** [comment]
@hemedani 

what worked for me, was within the jest config in package.json I added:

`"testEnvironment": "node"`

**Comment by hemedani** [comment]
yah `yarn start` is working

**Comment by philkeys** [comment]
@hemedani Hey, I wanted to let you know that I ended up switching from `"testEnvironment": "node"` to `"testURL": "http://localhost/"` later in the videos because the node setting was causing issues with the session testing in Jest—which is around video 16 or 17.

**Comment by hemedani** [comment]
Tanks @philkeys works like a charm
