### ISSUE TITLE
me returning null

### ISSUE THREAD

**Issue by yaldram** [benawad/graphql-ts-server-boilerplate#13]
Hi there , sir in my login resolver when i console.log req.session after session.userId = user.id i am able to see userId in my session object but in my me resolver i cannot access session.userId and also i am able to set keys in redis when i used the local express-session store instead of redis the same problem occured . Is there any problem with my express-session i tried it several times but same result Please help.

**Comment by benawad** [comment]
I'm guessing the cookie is not getting sent on the request for the me query and so it can't find the session for that user

**Comment by Anujraval24** [comment]
promise is in pending state, try to fix that by returning correct object use console.log at each step try to debug as much as possible

**Comment by yaldram** [comment]
Thankyou benawad sir and anuj sir for your response, i did a lot of console.logs in my login i get userId attached to session object but in me when i console.log session it only shows cookie and in my browser i can see cookie qid secondly when i run the server and go to localhost redis automatically adds keys whic is wierd. So i decided to explore from scratch again . Plus if i skipped redis and used express-sessions own store the same problem is occuring. I have tried it many times also got a lot frustrated, but i will do it from scratch once again Thanx.

**Comment by benawad** [comment]
If you use express-sessions own store be careful, it restarts every time your server does. When you store it in redis it will persist

**Comment by yaldram** [comment]
Thankyou sir for your response at last i found out the solution and it is to change graphql playground settings "request.credentials": "include" please anyone who faces this issue do this and give it a try

**Comment by agustif** [comment]
I'm also getting me: null, both on tests and on playground, I actually have redis and it's working, so I'm not sure what's missing/failing

**Comment by benawad** [comment]
@agustif my guess is the same cookie is not sent, you can verify this by checking the req headers and seeing what the value of the cookie is

**Comment by agustif** [comment]
Hey @benawad I'm not sure what's wrong.

If I console log response.request, I get this

```
    console.log src/modules/me/me.test.ts:79
      XMLHttpRequest {
        upload:
         XMLHttpRequestUpload { _ownerDocument: Document { location: [Getter/Setter] } },
        _registeredHandlers: Set { 'readystatechange' },
        _eventHandlers:
         [Object: null prototype] { readystatechange: [Function: handleLoad] },
        [Symbol(flag)]:
         { synchronous: false,
           withCredentials: true,
           mimeType: null,
           auth: null,
           method: 'POST',
           responseType: '',
           requestHeaders:
            { Accept: 'application/json, text/plain, */*',
              'Content-Type': 'application/json;charset=utf-8' },
           referrer: 'http://localhost/',
           uri: 'http://127.0.0.1:50091/',
           timeout: 0,
           body: undefined,
           formData: false,
           preflight: false,
           requestManager: RequestManager { openedRequests: [] },
           pool: undefined,
           agentOptions: undefined,
           strictSSL: undefined,
           proxy: undefined,
           cookieJar: CookieJar { enableLooseMode: true, store: { idx: {} } },
           encoding: 'UTF-8',
           origin: 'http://localhost',
           userAgent:
            'Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0' },
        [Symbol(properties)]:
         { beforeSend: false,
           send: true,
           timeoutStart: 0,
           timeoutId: 0,
           timeoutFn: null,
           client: null,
           responseHeaders:
            { 'X-Powered-By': 'Express',
              'Access-Control-Allow-Origin': 'http://localhost',
              Vary: 'Origin',
              'Access-Control-Allow-Credentials': 'true',
              'Content-Type': 'application/json',
              'Content-Length': '20',
              Date: 'Tue, 19 Mar 2019 23:06:49 GMT',
              Connection: 'close' },
           filteredResponseHeaders:
            [ 'X-Powered-By',
              'Access-Control-Allow-Origin',
              'Vary',
              'Access-Control-Allow-Credentials',
              'Content-Length',
              'Date',
              'Connection' ],
           responseBuffer:
            <Buffer 7b 22 64 61 74 61 22 3a 7b 22 6d 65 22 3a 6e 75 6c 6c 7d 7d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 1048526 more bytes>,
           responseCache: null,
           responseTextCache: '{"data":{"me":null}}',
           responseXMLCache: null,
           responseURL: 'http://127.0.0.1:50091/',
           readyState: 4,
           status: 200,
           statusText: 'OK',
           error: '',
           uploadComplete: true,
           uploadListener: false,
           abortError: false,
           cookieJar: CookieJar { enableLooseMode: true, store: { idx: {} } },
           bufferStepSize: 1048576,
           totalReceivedChunkSize: 20,
           requestBuffer: null,
           requestCache: null,
           origin: 'http://localhost' } }
```

The complete response
```
$ TS_NODE_FILES=true NODE_ENV=test jest --detectOpenHandles --notify --forceExit --runInBand
Determining test suites to run...Server is running on localhost:4000
 FAIL  src/modules/me/me.test.ts
  ● Console

    console.log src/modules/me/me.test.ts:79
      { data: { data: { me: null } },
        status: 200,
        statusText: 'OK',
        headers: { 'content-type': 'application/json' },
        config:
         { adapter: [Function: xhrAdapter],
           transformRequest: { '0': [Function: transformRequest] },
           transformResponse: { '0': [Function: transformResponse] },
           timeout: 0,
           xsrfCookieName: 'XSRF-TOKEN',
           xsrfHeaderName: 'X-XSRF-TOKEN',
           maxContentLength: -1,
           validateStatus: [Function: validateStatus],
           headers:
            { Accept: 'application/json, text/plain, */*',
              'Content-Type': 'application/json;charset=utf-8' },
           method: 'post',
           withCredentials: true,
           url: 'http://127.0.0.1:50149',
           data:
            '{"query":"\\n{\\n  me {\\n    id\\n    email\\n  }\\n}\\n"}' },
        request:
         XMLHttpRequest {
           upload: XMLHttpRequestUpload { _ownerDocument: [Document] },
           _registeredHandlers: Set { 'readystatechange' },
           _eventHandlers:
            [Object: null prototype] { readystatechange: [Function: handleLoad] },
           [Symbol(flag)]:
            { synchronous: false,
              withCredentials: true,
              mimeType: null,
              auth: null,
              method: 'POST',
              responseType: '',
              requestHeaders: [Object],
              referrer: 'http://localhost/',
              uri: 'http://127.0.0.1:50149/',
              timeout: 0,
              body: undefined,
              formData: false,
              preflight: false,
              requestManager: [RequestManager],
              pool: undefined,
              agentOptions: undefined,
              strictSSL: undefined,
              proxy: undefined,
              cookieJar: [CookieJar],
              encoding: 'UTF-8',
              origin: 'http://localhost',
              userAgent:
               'Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0' },
           [Symbol(properties)]:
            { beforeSend: false,
              send: true,
              timeoutStart: 0,
              timeoutId: 0,
              timeoutFn: null,
              client: null,
              responseHeaders: [Object],
              filteredResponseHeaders: [Array],
              responseBuffer:
               <Buffer 7b 22 64 61 74 61 22 3a 7b 22 6d 65 22 3a 6e 75 6c 6c 7d 7d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 1048526 more bytes>,
              responseCache: null,
              responseTextCache: '{"data":{"me":null}}',
              responseXMLCache: null,
              responseURL: 'http://127.0.0.1:50149/',
              readyState: 4,
              status: 200,
              statusText: 'OK',
              error: '',
              uploadComplete: true,
              uploadListener: false,
              abortError: false,
              cookieJar: [CookieJar],
              bufferStepSize: 1048576,
              totalReceivedChunkSize: 20,
              requestBuffer: null,
              requestCache: null,
              origin: 'http://localhost' } } }

  ● me › get current user

    expect(received).toEqual(expected)

    Difference:

    - Expected
    + Received

      Object {
    -   "me": Object {
    -     "email": "bob5@bob.com",
    -     "id": "82b0015f-3343-4d70-b081-fccedf443ebd",
    -   },
    +   "me": null,
      }

      79 |                console.log(response);
      80 |                // FIXME: {me: {id: userId, email}}
    > 81 |          expect(response.data.data).toEqual({ me: { id: userId, email } });
         |                                           ^
      82 |        });
      83 | });
      84 | 

      at Object.<anonymous> (src/modules/me/me.test.ts:81:30)
      at fulfilled (src/modules/me/me.test.ts:4:58)

 PASS  src/modules/login/login.test.ts
 PASS  src/modules/register/register.test.ts
 PASS  src/utils/createConfirmEmailLink.test.ts
 PASS  src/routes/confirmEmail.test.ts

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 10 passed, 11 total
Snapshots:   0 total
Time:        2.702s, estimated 3s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

00:07:41 with agustif in ~/Code/on  master [✘!?] is 📦  v0.0.1 via ⬢ v11.11.0 took
```

maybe there's something wrong with my me resolvers/query/middleware, but I double checked everything with the repo, and there are not any errors on typescript

**Comment by benawad** [comment]
@agustif is that the request for the me query? Looks like it's missing a cookie header, but I see the cookie jar. Log the request from the login and see if it has a set-cookie header. And then you can check the cookie jar to see if it's being stored

**Comment by broberson** [comment]
Had this issue again following along with the video. Code from this repo works, while code written following along does not. Changing `"axios": "^0.19.0"` in package.json to `"axios": "^0.18.0"` fixed the problem for me. Apparently they've broken something in more recent versions.
